---
- name: "Preflight check for OCP UPI install"
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - common
    
  tasks:
    - block:
      - name: Include tasks from db.yml
        include_tasks: db.yml
      tags: db


    - debug:
        var: hostvars[groups['dns'][0]].ip.split('.')[3]
...
