---
- name: "Confirm that pull secret file exists"
  stat:
    path: "{{ pullSecretFile }}"
  register: stat_result

- assert:
    fail_msg: "Pull secret file ({{ pullSecretFile }}) does not exist"
    that: stat_result.stat.exists

- name: "Confirm the HTTP server count"
  assert:
    that: groups['http']|length == 1
    fail_msg: "There should be exactly one http server specified."

- tempfile:
    state: file
  register: tempfile

- name: "Confirm that HTTP server is accessible"
  uri:
    url: "http://{{ hostvars[groups['http'][0]].inventory_hostname }}"
    return_content: no
    status_code: [200, 403]

- name: "Confirm that all RHCOS bootstrap images are available on HTTP server"
  get_url:
    url: "http://{{ hostvars[groups['http'][0]].inventory_hostname }}/{{ item }}"
    dest: "{{ tempfile.path }}"
  loop:
    - "{{ rhcos.initramfs }}"
    - "{{ rhcos.kernel }}"
    - "{{ rhcos.rootfs }}"

  loop_control:
    label: ""

- file:
    path: "{{ tempfile.path }}"
    state: absent
...