---
- name: "Generate the manifests"
  shell:
    cmd: "{{ installer }} create manifests --dir {{ outdir }}"

- name: "Save the generated manifests"
  copy:
    src: "{{ outdir }}/{{ item }}"
    dest: "{{ outdir }}/bak"
  loop:
    - manifests
    - openshift
...