---
- name: "Generate the manifests"
  shell:
    cmd: "{{ installer }} create manifests --dir {{ outdir }}/{{ clusterName }}"

- name: "Save the generated manifests"
  copy:
    src: "{{ outdir }}/{{ clusterName }}/{{ item }}"
    dest: "{{ outdir }}/{{ clusterName }}/bak/manifests"
  loop:
    - manifests
    - openshift
...