---
- name: "Confirm that bootstrap can listen on port ranges"
  wait_for:
    host: "{{ item[0] }}"
    port: "{{ item[1] }}"
    timeout: 1
  with_nested:
    - "{{ query('inventory_hostnames', 'bootstrap') }}"
    - "{{ hostvars[groups['bootstrap'][0]].portsToScan }}"
  tags: [ never, sentinel ]

- name: "Confirm that masters can listen on port ranges"
  wait_for:
    host: "{{ item[0] }}"
    port: "{{ item[1] }}"
    timeout: 1
  with_nested:
    - "{{ query('inventory_hostnames', 'masters') }}"
    - "{{ hostvars[groups['masters'][0]].portsToScan }}"
  tags: [ never, sentinel ]
...
