---
  - set_fact:
      fname: "bootstrap"

  - name: "Generate the {{ bitem }} bootstrap script"
    template:
      src: "templates/{{ bitem }}.template"
      dest: "{{ outdir }}/{{ clusterName }}/{{ hostvars[item].inventory_hostname_short }}-{{ clusterName }}.{{ bitem }}"
    loop: "{{ groups['bootstrap'] }}"

  - set_fact:
      fname: "master"

  - name: "Generate the {{ bitem }} master scripts"
    template:
      src: "templates/{{ bitem }}.template"
      dest: "{{ outdir }}/{{ clusterName }}/{{ hostvars[item].inventory_hostname_short }}-{{ clusterName }}.{{ bitem }}"
    loop: "{{ groups['masters'] }}"

  - set_fact:
      fname: "worker"

  - name: "Generate the {{ bitem }} worker scripts"
    template:
      src: "templates/{{ bitem }}.template"
      dest: "{{ outdir }}/{{ clusterName }}/{{ hostvars[item].inventory_hostname_short }}-{{ clusterName }}.{{ bitem }}"
    loop: "{{ groups['workers'] }}"
...