---
- block:
    - name: "Confirm that {{ outdir }}/{{ clusterName }} directories exist"
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ outdir }}/{{ clusterName }}/archive"
        - "{{ outdir }}/{{ clusterName }}/artifacts"

    - stat:
        path: "{{ outdir }}/{{ clusterName }}/artifacts/install-config.yaml"
      register: s

    - name: "Archive existing artifacts"
      archive:
        path: "{{ outdir }}/{{ clusterName }}/artifacts"
        dest: "{{ outdir }}/{{ clusterName }}/archive/{{ '%Y%m%d-%H%M' | strftime(s.stat.mtime) }}.tar.gz"
        exclude_path:
        - "{{ outdir }}/{{ clusterName }}/archive"
        remove: yes
      when: s.stat.exists is defined and s.stat.exists
  tags: [ always ]
...
