---
- name: "Setup output directory"
  include_tasks: tasks/outdir.yaml

- name: "Confirm installer"
  include_tasks: tasks/installer.yaml

- name: "Confirm key pair"
  include_tasks: tasks/keys.yaml

- name: "Generate DNS zone file"
  template:
    src: "templates/bind-zone.template"
    dest: "{{ outdir }}/{{ baseDomain }}.zone"
- pause:
    prompt: "Review this zone file ({{ outdir }}/{{ baseDomain }}.zone) and make sure your DNS matches!!"

- name: "Confirm DNS"
  include_tasks: tasks/dns.yaml

- name: "Confirm installer infrastructure"
  include_tasks: tasks/infra.yaml
...